=== arjun-prs/NCP_Project/scripts/sports.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="row" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="roll_no"/>
              <xs:element type="xs:string" name="sport1"/>
              <xs:element type="xs:string" name="sport2"/>
              <xs:element type="xs:string" name="sport3"/>
              <xs:element type="xs:string" name="sport4"/>
              <xs:element type="xs:string" name="sport5"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arjun-prs/NCP_Project/scripts/sports.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="sports.xsl" type:"text/xsl" ?>

<!DOCTYPE root [
<!ELEMENT root (row)+>
<!ELEMENT row (roll_no,sport1,sport2,sport3,sport4,sport5)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT sport1 (#PCDATA)>
<!ELEMENT sport2 (#PCDATA)>
<!ELEMENT sport3 (#PCDATA)>
<!ELEMENT sport4 (#PCDATA)>
<!ELEMENT sport5 (#PCDATA)>
]>
<root>
<!-- <root xmlns="https://w3schoools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="sports.xsd"> -->
  <row>
    <roll_no>CB.EN.U4CSE17401</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17402</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17403</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17404</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17405</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17406</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17407</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17408</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17409</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17410</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17411</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17412</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17413</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17414</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17415</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17416</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17417</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17418</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17419</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17420</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17421</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17422</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17423</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17424</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17425</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17426</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17427</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17428</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17429</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17430</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17431</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17432</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17433</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17434</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17435</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17436</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17437</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17438</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17439</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17440</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17441</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17442</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17443</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17444</roll_no>
    <sport1>Cricket</sport1>
    <sport2>Basketball</sport2>
    <sport3>Tennis</sport3>
    <sport4>Football</sport4>
    <sport5>Kabaddi</sport5>
  </row>
  <row>
    <roll_no>CB.EN.U4CSE17445</roll_no>
    <sport1>Cricket</sport1>
